Repository Open-Source-you/Hackotberfest2025, pull requests merged in 2022-10, with the labels that each got.

#7 Added animation on cards #2
  Card-Game/css/style.min.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#10 add mobile button
  Android-System-/style.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#12 Dice Game
  CONTRIBUTING.md
  Racing-Game/index.html
  Racing-Game/main.js
  Racing-Game/style.css
Labels: enhancement, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#14 stylist
  Online-HTML-CSS-Code-Editor/index.html
Labels: hacktoberfest-accepted, hacktoberfest2022

#15 add Some Css
  Online-HTML-CSS-Code-Editor/main.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#16 Added normal calculator (Issue #4)
  SimpleCalculator/index.html
  SimpleCalculator/index.js
  SimpleCalculator/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#18 add some button
  Grade-Calc/home.js
  Grade-Calc/sty.css
  Racing-Game/index.html
  Racing-Game/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#21 added button
  Grade-Calc/index.html
  Grade-Calc/sty.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#20 Login-Button-added-to-Online-HTML-CSS-Code-Editor
  Online-HTML-CSS-Code-Editor/index.html
  Online-HTML-CSS-Code-Editor/main.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#22 Adds countdown timer
  countdown-timer/README.md
  countdown-timer/assets/tones/Alarm05.wav
  countdown-timer/index.html
  countdown-timer/scripts/main.js
  countdown-timer/styles/style.css
Labels: hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#26 Merged Grade calculator and Simple calculator to a single webpage
  Grade & Simple-Calculator/home.js
  Grade & Simple-Calculator/index.html
  Grade & Simple-Calculator/sty.css
Labels: hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#31 Full_shooter_game
  Full_shooting_game/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#33 Intially show all cards
  Card-Game/script.js
Labels: hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#35 Update README.md
  README.md
  SimpleCalculator/index.html
  SimpleCalculator/style.css
  countdown-timer/index.html
  countdown-timer/styles/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#37 changed ui by changing css
  SimpleCalculator/style.css
Labels: hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#36 added new page: Snake Game
  Snake-Game/index.html
  Snake-Game/script.js
  Snake-Game/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#40 Added Levels in Card Game
  Card-Game/css/style.min.css
  Card-Game/images/birthdaycake.png
  Card-Game/images/cupcake.png
  Card-Game/images/dessert.png
  Card-Game/images/roll.png
  Card-Game/index.html
  Card-Game/script.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#39 Added social media hover animation
  .vscode/settings.json
  social media hover animation/index.html
  social media hover animation/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#41 some modification in CSS in calculator
  SimpleCalculator/index.html
  SimpleCalculator/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#43 adding new js file
  Shooter_Game/js/audio.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#44 adding bullet js file:
  Shooter_Game/js/bullet.js
  Shooter_Game/js/button.js
Labels: hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Hard

#42 add Hiding_content WebPage
  Hiding_content/index.css
  Hiding_content/index.html
  Hiding_content/index.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#46 adding definitions js file
  Shooter_Game/js/definitions.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#47 Added a Dice Game using Web Dev
  Dice_Game/DiceJS.js
  Dice_Game/DiceStyle.css
  Dice_Game/RollingDiceGame.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#48 add javascript
  Shooter_Game/js/jsfxr.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#49 action file
  Shooter_Game/js/hero.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#50 add game function
  Shooter_Game/js/game.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#51 add gaminmg file for javascript
  Shooter_Game/js/explosion.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#54 Added a new js file
  Grade & Simple-Calculator/home.js
  Shooter_Game/js/particle.js
  Shooter_Game/js/particleemitter.js
  SimpleCalculator/index.html
  SimpleCalculator/scientific calculator/index.html
  SimpleCalculator/scientific calculator/style.css
  SimpleCalculator/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#55 New JS file
  Shooter_Game/js/levelpop.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#59 daw
  dayofweek.html
  fallingbullete.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#60 waves
  slideimage.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#61 issuetracker
  IssueTracker.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Hard

#62 maths
  MathQuiz.html
Labels: help wanted, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Hard

#63 QR code
  QRCode.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#64 organised way
  html/IssueTracker.html
  html/MathQuiz.html
  html/QRCode.html
  html/colorpicker.html
  html/dayofweek.html
  html/fallingbullete.html
  html/slideimage.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#67 add Learn HTML CSS by my website
  Learn_HTML_CSS/index.css
  Learn_HTML_CSS/index.html
  Learn_HTML_CSS/index.js
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#68 add HTML BORDER
  HTML_BORDER/index.css
  HTML_BORDER/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#74 complete on project
  bulb light project/bulb.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#77 color picker
  bulb light project/auto-text.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, medium

#78 add style in css
  login_page/index.html
  login_page/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#79 Draw Hmtl
  html/draw.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#80 CSS some changes
  html/css.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#81 typing speed checker
  html/typing_speed_test.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#82 Yoga html webesite
  html/yoga.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, medium

#83 landing page styling
  home_page/index.html
  home_page/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, medium

#84 simple calculator
  calculator/index.html
  calculator/index.js
  calculator/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, medium

#70 Issue #65 Rock Paper Scissors
  Rock Paper Scissors/cp12.css
  Rock Paper Scissors/hp12.html
  Rock Paper Scissors/p12.js
  Rock Paper Scissors/paper.jpg
  Rock Paper Scissors/rock.jpg
  Rock Paper Scissors/scissor.jpg
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Hard

#85 Quiz app
  QuizApp/index.html
  QuizApp/script.js
  QuizApp/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#87 Survey form
  Survey form
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#90 BMI calculator
  BMI calculator/index.html
  BMI calculator/main.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#91 BMI calculator javascript file
  BMI calculator/script.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#92 tic-tac-toe game
  tic-tac-toe Game/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#93 tic-tac-toe game css and js file
  tic-tac-toe Game/script.js
  tic-tac-toe Game/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#96 html web
  html best web
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#97 css effects
  html best web
  html website/index.css
  html website/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Hard

#98 added javascript
  html website/index.js
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#99 User_Login
  .DS_Store
  html website/user_login.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#102 Added a folder of Hamburger menu animation
  Hamburger-menu-animation/index.html
  Hamburger-menu-animation/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#111 prince_verma
  HTML_BORDER/prince_verma/home.css
  HTML_BORDER/prince_verma/home.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#112 add some css
  HTML_BORDER/prince_verma/home.html
  html website/user_login.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#113 html for web
  HTML_BORDER/prince_verma/home.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#115 snake
  Snake-Game/gautam_snake_game/snake_game1.html
  Snake-Game/gautam_snake_game/snake_game2.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#117 snake_game3
  Snake-Game/gautam_snake_game/snake_game3.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#119 snake_game_final
  Snake-Game/gautam_snake_game/snake_game_final.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#120 tic_tae_toe_game
  tic-tac-toe Game/My Tic-Tac-Toe Game/home.html
  tic-tac-toe Game/My Tic-Tac-Toe Game/script.js
  tic-tac-toe Game/My Tic-Tac-Toe Game/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#122 Added my name in contributors. md
  CONTRIBUTING.md
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#123 Html web
  calculator/index.html
  html 0/1 website/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#125 jss file add
  html 0/1 website/index.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#126 html change
  html 0/1 website/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#127 Created HTML-tricks folder
  HTML-TRICKS/Inputs/index.html
  HTML-TRICKS/main.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#128 Created dialog example
  HTML-TRICKS/Dialog/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#129 Created datalist demo
  HTML-TRICKS/Datalist/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#130 create Readme.md for html tricks
  HTML-TRICKS/README.md
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest2022, Easy

#141 adding video.js file
  Shooter_Game/js/video.js
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#144 dice.html
  dice game react/dice.html
  dice game react/index.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#145 Create index.html
  HotelBooking/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#146 adding css files
  dice game react/dice1.png
  dice game react/dice2.png
  dice game react/dice3.png
  dice game react/dice4.png
  dice game react/dice5.png
  dice game react/dice6.png
  dice game react/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#147 my second req
  HotelBooking/Home.jsx
  HotelBooking/Hotel.jsx
  HotelBooking/List.jsx
  HotelBooking/home.css
  HotelBooking/hotel.css
  HotelBooking/list.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#148 react bmi calci
  simple calculator/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#149 zdfbAdd files via upload
  HotelBooking/login.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#150 adding css files
  simple calculator/main.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#151 my final req
  HotelBooking/useFetch.js
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#152 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#153 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#154 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#155 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Easy

#160 css add
  SimpleCalculator/style.css
Labels: enhancement, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#163 Added assets to Dice Game
  Dice_Game/DiceStyle.css
  Dice_Game/RollingDiceGame.html
  Dice_Game/img/dice1.png
  Dice_Game/img/dice2.png
  Dice_Game/img/dice3.png
  Dice_Game/img/dice4.png
  Dice_Game/img/dice5.png
  Dice_Game/img/dice6.png
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#162 Add files via upload
  Drum kit/images/crash.png
  Drum kit/images/kick.png
  Drum kit/images/snare.png
  Drum kit/images/tom1.png
  Drum kit/images/tom2.png
  Drum kit/images/tom3.png
  Drum kit/images/tom4.png
  Drum kit/index.html
  Drum kit/index.js
  Drum kit/run.js
  Drum kit/sounds/crash.mp3
  Drum kit/sounds/kick-bass.mp3
  Drum kit/sounds/snare.mp3
  Drum kit/sounds/tom-1.mp3
  Drum kit/sounds/tom-2.mp3
  Drum kit/sounds/tom-3.mp3
  Drum kit/sounds/tom-4.mp3
  Drum kit/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#164 Fixed height to make it less annoying
  Dynamic_calendar/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#165 Added the game of Othello
  Othello/index.html
  Othello/index.js
  Othello/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022

#166 Added the game of Snakes and Ladder
  SnakesAndladder/blackPiece.png
  SnakesAndladder/board.png
  SnakesAndladder/index.html
  SnakesAndladder/index.js
  SnakesAndladder/redPiece.png
  SnakesAndladder/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2022, Hard
