Repository Open-Source-you/Hackotberfest2025, pull requests merged in 2024-10, with the labels that each got.

#142 Added log in page UI (using HTML & CSS)
  Login Page/index.html
  Login Page/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#118 Create Alarm Clock
  Alarm-Clock/files/clock.svg
  Alarm-Clock/files/ringtone.mp3
  Alarm-Clock/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#175 Update user_login.html
  html website/user_login.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#161 Beautified login page
  Random Joke Generator/index.html
  Random Joke Generator/index.js
  Random Joke Generator/style.css
  login_page/index.html
  login_page/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#135 Cryptography Algorithm
  Crypto/BlackiqCryption.py
  Snake_Game_C/snake_game.cpp
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#179 updated Readme
  README.md
Labels: hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#178 Hackertoberfest 2024 contribute : to_do_list.html
  To do List/to_do_list.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy

#182 Contribution for Hackertoberfest2024 a random_word_game.html
  Random Word Game/random_word_game.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy

#187 Guess the number game using Html, Css, Javascript#185
  Guess the number/index.html
  Guess the number/script.js
  Guess the number/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#188 add flappy bird game
  flappy bird/index.html
  flappy bird/index.js
  flappy bird/logo.png
  flappy bird/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy

#189 Guess the Number Game
  NumberGuessGame/index.html
  NumberGuessGame/script.js
  NumberGuessGame/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy

#174 Update index.html
  BMI calculator/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#173 Create TicTacToe,java
  TicTacToe,java
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#191 Add AI Detective game
  AI_Detective_Game/ai_detective_game.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#186 feat: add 2048 project
  2048/app.js
  2048/arrow.png
  2048/index.html
  2048/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#194 Text to speech added
  Text-to-speech/.DS_Store
  Text-to-speech/Images/.DS_Store
  Text-to-speech/Images/dropdown.png
  Text-to-speech/Images/play.png
  Text-to-speech/README.md
  Text-to-speech/index.html
  Text-to-speech/script.js
  Text-to-speech/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#199 Flappy bird clone added
  flappy-bird-clone/Images/bottompipe.png
  flappy-bird-clone/Images/flappybird.png
  flappy-bird-clone/Images/flappybirdbg.png
  flappy-bird-clone/Images/toppipe.png
  flappy-bird-clone/README.md
  flappy-bird-clone/index.html
  flappy-bird-clone/script.js
  flappy-bird-clone/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy

#201 PDF summarization
  iris  flower/i.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#206 simon-says-done
  simonSays/index.html
  simonSays/script.js
  simonSays/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#203 Chat platform using Node js
  Chatplatform/.gitignore
  Chatplatform/README.md
  Chatplatform/index.js
  Chatplatform/package-lock.json
  Chatplatform/package.json
  Chatplatform/public/chat.html
  Chatplatform/public/css/style.css
  Chatplatform/public/index.html
  Chatplatform/public/js/main.js
  Chatplatform/utils/messages.js
  Chatplatform/utils/users.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#205 Optimize To-Do List App by simplifying JS logic and reducing DOM manipulation
  To do List/to_do_list.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#210 Solved Issue: #133 Snake Game in c++
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  Snake Game in C++/snake_game.cpp
  Snake Game in C++/snake_game.exe
  To Do App in JavaScript/app.js
  To Do App in JavaScript/index.html
  To Do App in JavaScript/style.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Hard

#216 Task Tracker Project
  Task Tracker Project/index.html
  Task Tracker Project/list.js
  Task Tracker Project/styles.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#220 Solved Issue: #108 Rock Papar Scissor game ML
  A real time rock paper scissor game ML/.gitignore
  A real time rock paper scissor game ML/.vscode/settings.json
  A real time rock paper scissor game ML/Approach.md
  A real time rock paper scissor game ML/LICENCE
  A real time rock paper scissor game ML/README.md
  A real time rock paper scissor game ML/RPS.py
  A real time rock paper scissor game ML/RPS_game.py
  A real time rock paper scissor game ML/Rock-paper-scissors.code-workspace
  A real time rock paper scissor game ML/gitpod.yml
  A real time rock paper scissor game ML/main.py
  A real time rock paper scissor game ML/pyproject.toml
  A real time rock paper scissor game ML/test_module.py
Labels: hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#218 Fixed issue #211 Gmail Clone
  gmail clone/gamil_logo.png
  gmail clone/index.html
  gmail clone/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Hard

#222 Solved Issue: #217 AIRLINE SYSTEM USING JAVA
  AIRLINE SYSTEM USING JAVA/.gitignore
  AIRLINE SYSTEM USING JAVA/build.xml
  AIRLINE SYSTEM USING JAVA/manifest.mf
  AIRLINE SYSTEM USING JAVA/nbproject/build-impl.xml
  AIRLINE SYSTEM USING JAVA/nbproject/genfiles.properties
  AIRLINE SYSTEM USING JAVA/nbproject/project.properties
  AIRLINE SYSTEM USING JAVA/nbproject/project.xml
  AIRLINE SYSTEM USING JAVA/src/airline/Add_Customer.java
  AIRLINE SYSTEM USING JAVA/src/airline/Cancel.java
  AIRLINE SYSTEM USING JAVA/src/airline/Flight_Info.java
  AIRLINE SYSTEM USING JAVA/src/airline/Journey_Details.java
  AIRLINE SYSTEM USING JAVA/src/airline/Login.java
  AIRLINE SYSTEM USING JAVA/src/airline/Mainframe.java
  AIRLINE SYSTEM USING JAVA/src/airline/Payment_Details.java
  AIRLINE SYSTEM USING JAVA/src/airline/conn.java
  AIRLINE SYSTEM USING JAVA/src/airline/mysql_commands.txt
  AIRLINE SYSTEM USING JAVA/src/icon/cancel.jpg
  AIRLINE SYSTEM USING JAVA/src/icon/cancel.png
  AIRLINE SYSTEM USING JAVA/src/icon/emp.png
  AIRLINE SYSTEM USING JAVA/src/icon/front.jpg
  AIRLINE SYSTEM USING JAVA/src/icon/front.png
  AIRLINE SYSTEM USING JAVA/src/icon/payment.png
  AIRLINE SYSTEM USING JAVA/src/icon/second.jpg
  Make a Game using any AI like Chatgpt and player is chatgpt/Mystery Adventure game/mystery_adventure.py
Labels: hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024

#224 Update index.html
  Alarm-Clock/index.html
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Hard

#226 minor change
  QuizApp/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy

#227 list remv
  QuizApp/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy

#228 add list
  QuizApp/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy

#229 Update index.js
  calculator/index.js
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy

#232 Adding Web Scraping gpt
  Web-Scrapping-Gpt/.venv
  Web-Scrapping-Gpt/ReadME.md
  Web-Scrapping-Gpt/Source code.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy

#219 Create Armstrong_number.java
  Armstrong_number.java
Labels: 10 Days For Review After Merge

#214 Python Calculator with GUI interface
  Python Calculator/GUI.png
  Python Calculator/simpleCalc.py
Labels: 10 Days For Review After Merge

#213 Create Weather.html
  WeatherApp/Weather.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, 10 Days For Review After Merge

#209 Create Guess the number game
  Guess the number.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, 10 Days For Review After Merge

#208 added Fibonacci using iteration
  fibonacci/Fibonacci using iteration.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, 10 Days For Review After Merge

#268 Simple Website in Html
  HTML Website/simpleweb.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#267 Hollow Diamond in C++
  CPP/Hollowdiamond.cpp
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#266 Hollow Diamond in java
  java/HollowDiamond.java
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#265 Add files via upload
  sjf.c
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#262 Added Chess game
  Chess
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#264 added the code for To do list
  To do List/To do list.html
  To do List/script.js
  To do List/styles.css
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#259 Create volume.generator.py
  Grade-Calc/volume.generator.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#263 Create simple C++ calculator
  C++_calculator/README.md
  C++_calculator/calculator.cpp
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#258 Create dinner.menu.py
  Grade-Calc/dinner.menu.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#257 Create pop.quiz.py
  QuizApp/pop.quiz.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All

#256 Create random.word.generator.py
  Random Word Game/random.word.generator.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2024, Easy, Open for All
