Repository Open-Source-you/Hackotberfest2025, pull requests merged in 2025-10, with the labels that each got.

#277 Added Gopika ASCII Banner project 🎉
  .github/ISSUE_TEMPLATE/name_ASCII_Banner/README.md
  .github/ISSUE_TEMPLATE/name_ASCII_Banner/banner.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy

#280 Update README.md
  HTML-TRICKS/README.md
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025

#281 Update app.js
  2048/app.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hard

#282 Update style.css
  Cafe Landing Page/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025

#283 Update build.xml
  AIRLINE SYSTEM USING JAVA/build.xml
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy

#287 landing index.html
  Cafe Landing Page/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hard

#288 Update index.html
  2048/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hard

#290 Update script.js
  Guess the number/script.js
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025

#275 extract and plot csv data - python
  .DS_Store
  DS - extract and plot data/.DS_Store
  DS - extract and plot data/data.csv
  DS - extract and plot data/extractandplot.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hard

#301 add button
  BMI calculator/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hard

#304 Update script.js
  BMI calculator/script.js
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hard

#303 main.css burtton
  BMI calculator/main.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hard

#302 Update main.css
  BMI calculator/main.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hard

#306 Update script.js
  BMI calculator/script.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hard

#307 Update index.html
  Alarm-Clock/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hard, 10 Days For Review After Merge

#311 Update Main.java
  Guess the word game/Main.java
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025

#312 Update ai_detective_game.py
  AI_Detective_Game/ai_detective_game.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025

#333 Python Algorithm
  movezero.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hackotberfest-2025

#327 Feature : pomodoro timer
  pomodoro-timer/README.md
  pomodoro-timer/pomodoro.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hackotberfest-2025

#329 This project helps us to create a Public API for ML model using Flask and ngrok service and helps us to access the API anywhere from the net!
  ML_model_as_PublicAPI/Deploying_ML_model_as_public_API_ngrok.ipynb
  ML_model_as_PublicAPI/README_solar_API.md
  ML_model_as_PublicAPI/SVR_model_solar.ipynb
  ML_model_as_PublicAPI/desktop.ini
  ML_model_as_PublicAPI/solar_svr_model.joblib
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hackotberfest-2025

#313 adding bubble sort code
  Java/Sorts/BubbleSort.java
  Java/Sorts/BubbleSortMain.java
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hackotberfest-2025

#248 RealTime ChatApp
  RealTime-ChatApp/.gitignore
  RealTime-ChatApp/backend/.env.example
  RealTime-ChatApp/backend/.gitignore
  RealTime-ChatApp/backend/config/database.js
  RealTime-ChatApp/backend/controllers/messageController.js
  RealTime-ChatApp/backend/controllers/userController.js
  RealTime-ChatApp/backend/index.js
  RealTime-ChatApp/backend/middleware/isAuthenticated.js
  RealTime-ChatApp/backend/models/conversationModel.js
  RealTime-ChatApp/backend/models/messageModel.js
  RealTime-ChatApp/backend/models/userModel.js
  RealTime-ChatApp/backend/package.json
  RealTime-ChatApp/backend/routes/messageRoute.js
  RealTime-ChatApp/backend/routes/userRoute.js
  RealTime-ChatApp/backend/socket/socket.js
  RealTime-ChatApp/frontend/.gitignore
  RealTime-ChatApp/frontend/README.md
  RealTime-ChatApp/frontend/package.json
  RealTime-ChatApp/frontend/src/App.js
  RealTime-ChatApp/frontend/src/components/HomePage/HomePage.jsx
  RealTime-ChatApp/frontend/src/components/Login/Login.jsx
  RealTime-ChatApp/frontend/src/components/Message/Message.jsx
  RealTime-ChatApp/frontend/src/components/MessageContainer/MessageContainer.jsx
  RealTime-ChatApp/frontend/src/components/Messages/Messages.jsx
  RealTime-ChatApp/frontend/src/components/OtherUser/OtherUser.jsx
  RealTime-ChatApp/frontend/src/components/OtherUsers/OtherUsers.jsx
  RealTime-ChatApp/frontend/src/components/SendInput/SendInput.jsx
  RealTime-ChatApp/frontend/src/components/Sidebar/Sidebar.jsx
  RealTime-ChatApp/frontend/src/components/Signup/Signup.jsx
  RealTime-ChatApp/frontend/src/hooks/useGetAuthUser.jsx
  RealTime-ChatApp/frontend/src/hooks/useGetMessages.jsx
  RealTime-ChatApp/frontend/src/hooks/useGetOtherUsers.jsx
  RealTime-ChatApp/frontend/src/hooks/useGetRealTimeMessage.jsx
  RealTime-ChatApp/frontend/src/index.css
  RealTime-ChatApp/frontend/src/index.js
  RealTime-ChatApp/frontend/src/redux/messageSlice.js
  RealTime-ChatApp/frontend/src/redux/socketSlice.js
  RealTime-ChatApp/frontend/src/redux/store.js
  RealTime-ChatApp/frontend/src/redux/userSlice.js
  RealTime-ChatApp/frontend/src/routes/Allroutes.jsx
  RealTime-ChatApp/frontend/src/validators/loginValidation.js
  RealTime-ChatApp/frontend/src/validators/signupValidation.js
  RealTime-ChatApp/frontend/tailwind.config.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Open for All

#336 Update index.html
  2048/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hackotberfest-2025

#342 Commit Update index.html
  Learn_HTML_CSS/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hard, Hackotberfest-2025

#347 Update ai_detective_game.py
  AI_Detective_Game/ai_detective_game.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hackotberfest-2025

#348 Update ai_detective_game.py
  AI_Detective_Game/ai_detective_game.py
  Android-System-/main.js
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hackotberfest-2025

#350 marge
  Anti-Malware_application/anti-malware.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hard, Hackotberfest-2025

#351 css
  BMI calculator/main.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hard, Hackotberfest-2025

#352 cpp
  C++_calculator/calculator.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hackotberfest-2025

#354 Update index.html
  Cafe Landing Page/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hackotberfest-2025

#361 Update index.js
  html 0/1 website/index.js
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hackotberfest-2025

#293 Added Etch-a-Sketch game using JS,HTML,CSS
  Etch-A-Sketch/Image Resources/night.jpg
  Etch-A-Sketch/README.md
  Etch-A-Sketch/index.html
  Etch-A-Sketch/script.js
  Etch-A-Sketch/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hackotberfest-2025

#334 password_generator.py
  password_generator.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hackotberfest-2025

#366 Update index.html
  2048/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hackotberfest-2025

#371 Update gitpod.yml
  A real time rock paper scissor game ML/gitpod.yml
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hackotberfest-2025

#370 index.html
  SnakesAndladder/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hackotberfest-2025

#368 Update RPS_game.py
  A real time rock paper scissor game ML/RPS_game.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hackotberfest-2025

#367 Update mystery_adventure.py
  Make a Game using any AI like Chatgpt and player is chatgpt/Mystery Adventure game/mystery_adventure.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, Hackotberfest-2025

#373 Update WikiLLM.py
  WikiLLM/WikiLLM.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Hackotberfest-2025

#378 Update index.js
  SimpleCalculator/index.js
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, medium, Hackotberfest-2025

#374 Update random.word.generator.py
  Random Word Game/random.word.generator.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest, hacktoberfest2025, Easy, medium, Hackotberfest-2025

#385 Add JavaScript Password Manager project
  Password Manager/index.html
  Password Manager/script.js
  Password Manager/style.css
Labels: invalid, spam

#379 i just add 2 algo in python, Happy hacking
  Dynamic-Programming-python/BitmaskDynamicProgrammingApproach.py
  Dynamic-Programming-python/longest_common_substring.py
Labels: invalid, spam
